name: Build, test and tag the api
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '.metadata'
      - 'README.md'
      - '.github/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20.0'
      - name: Download libraries
        run: go mod download
      - name: Download staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      # --- BUILD API
      - name: Go build
        run: go build .

      # --- CHECKS
      - name: Unit tests
        run: go test ./...
      - name: Lint
        run: staticcheck ./...

  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        run: "echo \"VERSION=$(cat version.yaml | tr -d 'version: ')\" >> $GITHUB_ENV"
      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/` + version,
                sha: context.sha
            })
